#!/usr/bin/env python3
"""Build kb.js by embedding the curated guideline knowledge into the static site.

Run:  python3 build.py     (re-run whenever the source knowledge changes)

SAFETY: this reads ONLY specific files under the main project's knowledge/ tree
(ASFA, blood prep, coag CDS, transfusion reactions). It NEVER touches the app's
data/ directory, so no PHI can ever be embedded. Embedding (rather than fetching
JSON) lets the site open straight from a file:// double-click, with no server.
"""

from __future__ import annotations

import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
# Default: sibling checkout at ~/Projects/tm-coag-logger. Override with env var.
KNOWLEDGE = os.environ.get("TMCOAG_KNOWLEDGE") or os.path.join(
    HERE, "..", "tm-coag-logger", "tmcoag", "knowledge"
)

MODULES = {
    "asfa": "asfa/asfa_indications.json",
    "asfaProtocols": "asfa/asfa_protocols.json",
    "bloodprep": "bloodprep/bloodprep.json",
    "coag": "coag_tests/coag_cds.json",
    "reactions": "transfusion_reactions/transfusion_reactions.json",
}

# Defensive: if any of these keys appear at the top level of a loaded file, abort
# — they would indicate a patient-data file slipped in.
PHI_SMELL = {"case_log", "entries", "mrn", "patient_name", "accession_id", "daylog"}


def main() -> int:
    kb = {}
    for key, rel in MODULES.items():
        path = os.path.join(KNOWLEDGE, rel)
        if not os.path.isfile(path):
            print(f"WARN: missing {path} — '{key}' will be absent", file=sys.stderr)
            continue
        with open(path, encoding="utf-8") as fh:
            data = json.load(fh)
        if isinstance(data, dict) and PHI_SMELL & set(data.keys()):
            print(f"ABORT: {path} has PHI-like top-level keys; refusing to embed.", file=sys.stderr)
            return 2
        kb[key] = data

    kb_js = ("// AUTO-GENERATED by build.py — do not edit by hand.\n"
             "// Embedded transfusion-medicine & coagulation GUIDELINE knowledge (no PHI).\n"
             "window.KB = " + json.dumps(kb, ensure_ascii=False, separators=(",", ":")) + ";\n")
    out = os.path.join(HERE, "kb.js")
    with open(out, "w", encoding="utf-8") as fh:
        fh.write(kb_js)
    print(f"wrote {out}  ({os.path.getsize(out):,} bytes)  modules: {list(kb.keys())}")

    # Also emit a SINGLE self-contained file (CSS + data + JS inlined) — the
    # easiest thing to share: open by double-click, works offline, e-mailable.
    try:
        css = _read(os.path.join(HERE, "styles.css"))
        app = _read(os.path.join(HERE, "app.js"))
        html = _read(os.path.join(HERE, "index.html"))
        html = html.replace('<link rel="stylesheet" href="styles.css" />', f"<style>\n{css}\n</style>")
        html = html.replace('<script src="kb.js"></script>', f"<script>\n{kb_js}\n</script>")
        html = html.replace('<script src="app.js"></script>', f"<script>\n{app}\n</script>")
        single = os.path.join(HERE, "tmcoag-reference.html")
        with open(single, "w", encoding="utf-8") as fh:
            fh.write(html)
        print(f"wrote {single}  ({os.path.getsize(single):,} bytes)  — single-file, open offline")
    except FileNotFoundError as exc:
        print(f"WARN: single-file build skipped ({exc})", file=sys.stderr)
    return 0


def _read(p: str) -> str:
    with open(p, encoding="utf-8") as fh:
        return fh.read()


if __name__ == "__main__":
    raise SystemExit(main())
